site_name: Metadata Menu
theme:
  name: material
  logo: assets/obsidian.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue-grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - General Concepts: general.md
  - Controls: controls.md
  - Settings: settings.md
  - FileClasses: fileclasses.md
  - API: api.md

repo_url: https://github.com/mdelobelle/metadata-menu

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.tabbed
